version: "3.8"
services:
  nginx:
    container_name: hk-nginx
    image: nginx:1.13
    restart: always
    ports:
      - 80:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  app:
    image: ghcr.io/alexmeh96/vkbot-app-image:${DOCKER_TAG}
    container_name: "app"
    environment:
      - VK_BOT_TOKEN=${VK_BOT_TOKEN}
      - VK_BOT_GROUP_ID=${VK_BOT_GROUP_ID}
      - VK_BOT_CODE_ANSWER_SERVER=${VK_BOT_CODE_ANSWER_SERVER}
    restart: always
    ports:
      - 8080:8080